Correct some strange word usage
MicrosoftDocs/visualstudio-docs pull request #5924
Opened 2020-09-28 09:55 UTC by Woebin

2020-09-28 09:56 UTC, PRMerger20 commented
@Woebin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-09-28 18:23 UTC, TerryGLee requested changes

2020-09-28 18:23 UTC, TerryGLee commented on docs/ide/reference/how-to-use-the-keyboard-exclusively.md
> +> Depending on your settings or the edition of Visual Studio you use, the dialog boxes and menu commands you see might differ from those described in Help. To change your settings, select **Import an
We appreciate your taking the time to create a PR! We'd like to ask for a few changes, though. Starting with the following:

Please note that our convention is that items are "on" a menu. See the examples in here: [https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods#multiple-input-methods-and-branching-within-procedures](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-alternative-input-methods#multiple-input-methods-and-branching-within-procedures)

2020-09-28 18:23 UTC, TerryGLee commented on docs/ide/reference/how-to-use-the-keyboard-exclusively.md
> +- To move among files in an editor or designer, use the **Ctrl**+**Tab** keyboard shortcut to display the IDE Navigator with **Active Files** selected. Use the **Enter** key to navigate to the highli
Please change instances of "Use the **Enter** key" to "Press the **Enter** key." In other words, we use the verb "press" in an imperative statement regarding specific keys on a keyboard. (The first instance of "use the _x_ shortcut" is fine, however.) 

This is also per examples in the guidance link listed in the previous comment.

2020-09-28 18:23 UTC, TerryGLee commented on docs/ide/reference/how-to-use-the-keyboard-exclusively.md
> +- To move among docked tool windows, use the **Alt**+**F7** keyboard shortcut to display the IDE Navigator with **Active Tool Windows** selected. Use the **Enter** key to navigate to the highlighted
Same comment about "Use the Enter key" ... please change the verb "use" to "press" . Thanks!

2020-10-16 17:24 UTC, TerryGLee commented
@Woebin Thanks again for your PR. We requested changes to your original PR but haven't heard back; so, to address that which you've noted, we've created our own internal PR to capture most of your suggested changes, which will be published live after 4:00pm PDT today (10/16/2020). Meanwhile, we'll close this PR, with our thanks to you for helping to improve our documentation.

2020-10-16 17:24 UTC, closed without merging

2020-10-16 17:44 UTC, Woebin commented
> @Woebin Thanks again for your PR. We requested changes to your original PR but haven't heard back; so, to address that which you've noted, we've created our own internal PR to capture most of your suggested changes, which will be published live after 4:00pm PDT today (10/16/2020). Meanwhile, we'll close this PR, with our thanks to you for helping to improve our documentation.
Hi! I'm really sorry, it seems I either didn't get notification emails for the comments or they ended up in spam, so I honestly just forgot about this until right now. I'm absolutely in favor of you taking my suggestions and using them in a separate PR though, I'm just glad I could be of help even though I failed to respond in a timely manner (again, sorry about that; I'll have to check my notification settings for the future).

2020-10-19 19:03 UTC, TerryGLee commented
@Woebin No worries! We always appreciate PRs that folks send our way. We look forward to hearing from you again. :)