Updated the Note field for adding the encodings to make it readable.
MicrosoftDocs/visualstudio-docs pull request #5995
Opened 2020-10-17 08:03 UTC by bmarshalsea

It is difficult to follow the direction as a single block of text. Split into corresponding dialog boxes, to allow easier following.

2020-10-17 08:03 UTC, PRMerger6 commented
@bmarshalsea : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-19 19:01 UTC, TerryGLee requested changes

2020-10-27 22:43 UTC, TerryGLee approved these changes

2020-10-27 22:43 UTC, PRMerger17 commented
@TerryGLee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-27 22:44 UTC, merged