Update format-specifiers-in-cpp.md
MicrosoftDocs/visualstudio-docs pull request #6705
Opened 2021-05-24 21:35 UTC by hharshada

Added new specifier information.

2021-05-24 21:35 UTC, PRMerger20 commented
@hharshada : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-05-24 22:17 UTC, Mikejo5000 commented on docs/debugger/format-specifiers-in-cpp.md
> +|handle|displays information about win32 handle|0x000000000000009c| Dispalys available useful information about handle such as Thread Id etc. |
```suggestion
|handle|displays information about win32 handle|0x000000000000009c| Displays useful information about handle such as thread ID, etc. |
```

2021-05-24 22:21 UTC, PRMerger15 commented
@hharshada : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-05-24 22:22 UTC, Mikejo5000 requested changes
@hharshada A couple of minor edits. On GitHub, you can commit them from the **Files changed** tab. (After you commit, you can pull the change to your local copy. In the git command line, that would be something like "git pull origin patch-3", but it depends on your setup.)

2021-06-05 22:44 UTC, j-martens commented
@hharshada - do you want to fix or close this pull request? Thank you!

2021-06-07 16:45 UTC, hharshada commented
Hey Mike,

I think I made a suggested fix for this already.


From: Josée Martens ***@***.***>
Sent: Saturday, June 5, 2021 3:45 PM
To: MicrosoftDocs/visualstudio-docs ***@***.***>
Cc: Harshada Chandrakant Hole ***@***.***>; Mention ***@***.***>
Subject: Re: [MicrosoftDocs/visualstudio-docs] Update format-specifiers-in-cpp.md (#6705)


@hharshada<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhharshada&data=04%7C01%7CHarshada.Hole%40microsoft.com%7C72b824b460804c93980608d928737d11%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637585298750985184%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xc8mmdKIp%2FZWMJ%2BeFwXwEtPahyX3V%2ByMKyBQBRcXdSQ%3D&reserved=0> - do you want to fix or close this pull request? Thank you!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fvisualstudio-docs%2Fpull%2F6705%23issuecomment-855305877&data=04%7C01%7CHarshada.Hole%40microsoft.com%7C72b824b460804c93980608d928737d11%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637585298750995198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bEaUV00tVH1vDvLAGlF%2FzDz6g2r7mNJBXvcan%2BUBPAQ%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAPKMJDLJVOVVLNIBACK2HE3TRKSFDANCNFSM45N7U54A&data=04%7C01%7CHarshada.Hole%40microsoft.com%7C72b824b460804c93980608d928737d11%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637585298750995198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cnWtOSCHbG0NEBJHHbItNXqcr%2FnP17SbZgmzUcjVg%2F8%3D&reserved=0>.

2021-06-07 22:23 UTC, Mikejo5000 commented on docs/debugger/format-specifiers-in-cpp.md
> +|handle|displays information about win32 handle|0x000000000000009c| Displays useful information about handle such as thread ID, etc. |
```suggestion
|handle|Displays information about win32 handle|0x000000000000009c| Displays useful information about handle such as thread ID, etc. |
```

2021-06-07 22:23 UTC, PRMerger15 commented
@Mikejo5000 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2021-06-07 22:24 UTC, Mikejo5000 approved these changes
Thanks!

2021-06-07 22:24 UTC, Mikejo5000 commented
#sign-off

2021-06-08 14:57 UTC, merged