Add documentation for [DeploymentItem] attribute
MicrosoftDocs/visualstudio-docs pull request #8927
Opened 2023-02-06 13:58 UTC by engyebrahim

fix: https://github.com/microsoft/testfx/issues/1320

2023-02-06 14:00 UTC, engyebrahim commented
Hi @Mikejo5000, please wait before merging until @Evangelink approve too.

2023-02-06 17:36 UTC, Court72 commented
@Mikejo5000, @Evangelink  

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-02-07 19:14 UTC, Mikejo5000 commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +And here you can see its [constructors](<xref:microsoft.visualstudio.testtools.unittesting.deploymentitemattribute#constructors>).
```suggestion
And here you can see its [constructors](<xref:Microsoft.VisualStudio.TestTools.UnitTesting.DeploymentItemAttribute#constructors>).
```

2023-02-07 19:16 UTC, Mikejo5000 commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +And here you can see its [constructors](<xref:microsoft.visualstudio.testtools.unittesting.deploymentitemattribute#constructors>).
Looks like the xref is case sensitive. Also, I don't recall seeing bookmark/anchor links in an xref, so you might have to remove the "#constructors" portion to get the link to work correctly.

2023-02-10 09:14 UTC, Evangelink commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +The <xref:Microsoft.VisualStudio.TestTools.UnitTesting.DeploymentItemAttribute> for copying files or folders specified as deployment items to the deployment directory. Deployment directory is where a
What is starting with MSTest v2? Is it the attribute or the copy or all?

2023-02-10 09:14 UTC, Evangelink commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +The <xref:Microsoft.VisualStudio.TestTools.UnitTesting.DeploymentItemAttribute> for copying files or folders specified as deployment items to the deployment directory. Deployment directory is where a
```suggestion
The <xref:Microsoft.VisualStudio.TestTools.UnitTesting.DeploymentItemAttribute> for copying files or folders specified as deployment items to the deployment directory. Deployment directory is where all the deployment items are present along with test project dll. (starting from MSTest v2)
```

2023-02-10 09:14 UTC, Evangelink commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +// without adding a custom output path the copied files will be in TestResults folder inside the project folder
I would remove this comment here and add it in the explanation above (see previous comment).

2023-02-10 09:14 UTC, Evangelink commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +[DeploymentItem(@"C:\classLevelDepItem.xml")]   //absolute path
```suggestion
[DeploymentItem(@"C:\classLevelDepItem.xml")]   // Copy file using some absolute path
```

2023-02-10 09:14 UTC, Evangelink commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +    [DeploymentItem(@"..\..\methodLevelDepItem1.xml")]   //relative path to the dll location
```suggestion
    [DeploymentItem(@"..\..\methodLevelDepItem1.xml")]   // Copy file using a relative path from the dll output location
```

2023-02-10 09:14 UTC, Evangelink commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +    [DeploymentItem(@"C:\DataFiles\methodLevelDepItem2.xml", "DataFiles")]   //custom output path
```suggestion
    [DeploymentItem(@"C:\DataFiles\methodLevelDepItem2.xml", "SampleDataFiles")]   // File will be added under a SampleDataFiles in the deployment directory
```

2023-02-10 10:33 UTC, Evangelink approved these changes

2023-02-10 10:35 UTC, Evangelink approved these changes

2023-02-13 18:36 UTC, Mikejo5000 commented on docs/test/using-microsoft-visualstudio-testtools-unittesting-members-in-unit-tests.md
> +The MSTest V2 framework introduced <xref:Microsoft.VisualStudio.TestTools.UnitTesting.DeploymentItemAttribute> for copying files or folders specified as deployment items to the deployment directory (
```suggestion
The MSTest V2 framework introduced <xref:Microsoft.VisualStudio.TestTools.UnitTesting.DeploymentItemAttribute> for copying files or folders specified as deployment items to the deployment directory (without adding a custom output path the copied files will be in TestResults folder inside the project folder). The deployment directory is where all the deployment items are present along with test project DLL.
```

2023-02-13 18:38 UTC, Mikejo5000 requested changes
@engyebrahim Minor edits suggested. Is this PR also waiting for the MSTest v4 update? Or is it ready to merge?

2023-02-14 08:39 UTC, engyebrahim commented
Hi @Mikejo5000, this one is ready to merge

2023-02-22 19:18 UTC, Mikejo5000 approved these changes

2023-02-22 19:18 UTC, Mikejo5000 commented
#sign-off Thanks!

2023-02-22 22:25 UTC, merged