Update DIA SDK filepaths and DLL names
MicrosoftDocs/visualstudio-docs pull request #9213
Opened 2023-05-08 05:19 UTC by mavaddat

I have updated the filepaths and updated the DLL names for the Debug Interface Access (DIA) SDK docs with examples from Visual Studio 2022. These are from my own system
I calculated the paths using the following helper script that I wrote in PowerShell:

```pwsh
Get-ChildItem -Path "$env:ProgramFiles\Microsoft Visual Studio\" -Filter 'msdia*dll' -Recurse | ForEach-Object {
    $diaPath = $_.FullName
    foreach ($vsVar in Get-ChildItem -Path Env:\ | Where-Object -FilterScript { $_.Name -match 'visual' -or $_.Value -match 'visual' -and (Test-Path -Path $_.Value) } | ForEach-Object {
            [pscustomobject]@{
                Length = $_.Value.Length
                Name   = $_.Name
                Value  = $_.Value
            }
        } | Sort-Object -Descending -Property Length )
    {
        $diaPath = $diaPath -replace ([regex]::Escape(($vsVar.Value))), ('%' + $vsVar.Name + '%\')
    }
    $diaPath | Write-Output
} | Sort-Object -Unique
```

2023-05-08 15:47 UTC, Court72 commented
@Mikejo5000

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2023-05-08 21:13 UTC, Mikejo5000 commented on docs/debugger/debug-interface-access/getting-started-debug-interface-access-sdk.md
> +  - `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK\bin\msdia140.dll` (default)
```suggestion
  - `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK\bin\msdia140.dll` (x86)
```

2023-05-08 21:15 UTC, Mikejo5000 commented on docs/debugger/debug-interface-access/getting-started-debug-interface-access-sdk.md
> +  As part of the installation, the `msdia140.dll`, which implements the DIA SDK, is automatically registered so all that you need to do to use it is to include `dia2.h` in your program and link to `d
```suggestion
  As part of the installation, the `msdia140.dll`, which implements the DIA SDK, is automatically registered so all that you need to do to use it is to include `dia2.h` in your program and link to `diaguids.lib`.
```

2023-05-08 21:17 UTC, Mikejo5000 commented on docs/debugger/debug-interface-access/getting-started-debug-interface-access-sdk.md
> +  As part of the installation, the `msdia140.dll`, which implements the DIA SDK, is automatically registered so all that you need to do to use it is to include `dia2.h` in your program and link to `d
@mavaddat Apparently, this is no longer true so can be removed

2023-05-08 21:18 UTC, Mikejo5000 requested changes
@mavaddat I put in a few GitHub suggestions requested by one of the devs. Thanks for the contribution! Looks good. Please use the **Commit suggestion** buttons to add the suggestions.

2023-05-09 17:01 UTC, Mikejo5000 commented on docs/debugger/debug-interface-access/getting-started-debug-interface-access-sdk.md
> +  - `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK\bin\msdia140.dll` (default)
```suggestion
  - `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK\bin\msdia140.dll` (x86)
```

2023-05-09 17:37 UTC, Mikejo5000 approved these changes

2023-05-09 17:38 UTC, Mikejo5000 commented
#sign-off Thanks, @mavaddat !

2023-05-09 20:27 UTC, merged